apiVersion: v1
kind: Namespace
metadata:
  name: irrigation-production
  labels:
    name: irrigation-production
---
apiVersion: v1
kind: Namespace
metadata:
  name: irrigation-staging
  labels:
    name: irrigation-staging
